name: wave_progress_indicator
description: A customizable wave-style progress indicator for Flutter apps.
version: 0.0.1
repository: https://github.com/MuntasirAsif/wave_progress_indicator
issue_tracker: https://github.com/MuntasirAsif/wave_progress_indicator/issues
documentation: https://github.com/MuntasirAsif/wave_progress_indicator#readme

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  assets:
    - asset/preview-1.gif
    - asset/preview-2.gif
