name: Flutter Package CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # optional: enable auto-publish only on version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test

      # Optional: Publish to pub.dev only if this is a tag push
      - name: Restore pub.dev credentials
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p ~/.pub-cache
          echo "${{ secrets.PUB_DEV_CREDENTIALS }}" > ~/.pub-cache/credentials.json

      - name: Publish to pub.dev
        if: startsWith(github.ref, 'refs/tags/v')
        run: flutter pub publish --force